apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: dev
  labels:
    app: rancher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: rancher
#        version: ${BUILD_NUMBER}
    spec:
      containers:
      - image: rancher/rancher:latest
        imagePullPolicy: Always
        name: rancher
        ports:
        - containerPort: 80
          name: rancher
        readinessProbe:
#          tcpSocket:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
#          tcpSocket:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/lib/rancher
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: rancher-ebs-claim
