apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-ebs-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 3Gi
